use Project;

create table Project.login as select * from login_form20march.login;
create table Project.Attendance as select * from attendance_form_27.Attendance;
create table Project.Attendance_month_master as select * from attendance_form_27.Attendance_month_master;
create table Project.Exam as select * from attendance_form_27.Exam;
create table Project.Exam_master as select * from attendance_form_27.Exam_master;
create table Project.Student_master as select * from attendance_form_27.Student_master;
create table Project.Subject_master as select * from attendance_form_27.Subject_master;

ALTER TABLE Exam
ADD FOREIGN KEY (Student_ID) REFERENCES Student_master(Student_ID);

ALTER TABLE  Exam
ADD FOREIGN KEY (Exam_type_ID) REFERENCES Exam_master(Exam_type_ID);

ALTER TABLE  Exam
ADD FOREIGN KEY (Subject_ID) REFERENCES Subject_master(Subject_ID);
create table Project.all_cities as select * from job_application_form_07_march.all_cities;
create table Project.all_states as select * from job_application_form_07_march.all_states;


CREATE TABLE `JOB_APPLICATION_FORM` (
  `INDEX_NO` int NOT NULL AUTO_INCREMENT,
  `F_NAME` varchar(45) DEFAULT NULL,
  `L_NAME` varchar(45) DEFAULT NULL,
  `ADDRESS_1` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PHONE_NO` bigint DEFAULT NULL,
  `CITY_NAME` varchar(45) DEFAULT NULL,
  `CITY_CODE` bigint DEFAULT NULL,
  `GENDER` varchar(10) DEFAULT NULL,
  `RELATIONSHIP` varchar(10) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `Designation` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`INDEX_NO`),
  UNIQUE KEY `INDEX_NO` (`INDEX_NO`),
  UNIQUE KEY `EMAIL` (`EMAIL`),
  CONSTRAINT `JOB_APPLICATION_FORM_ibfk_1` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=184 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `EDUCATION` (
  `EDUCATION_NO` int NOT NULL AUTO_INCREMENT,
  `INDEX_NO` int DEFAULT NULL,
  `EDUCATION_TYPE` varchar(45) DEFAULT NULL,
  `BORD_NAME` varchar(45) DEFAULT NULL,
  `PASS_YEAR` int DEFAULT NULL,
  `PERCENTAGE` float DEFAULT NULL,
  PRIMARY KEY (`EDUCATION_NO`),
  UNIQUE KEY `EDUCATION_NO` (`EDUCATION_NO`),
  KEY `EDUCATION_TYPE` (`EDUCATION_TYPE`),
  KEY `INDEX_NO` (`INDEX_NO`),
  CONSTRAINT `EDUCATION_ibfk_1` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `INDEX_NO` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`)
) ENGINE=InnoDB AUTO_INCREMENT=174 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `KNOWN_LANGUAGE` (
  `LANGUAGE_ID` int NOT NULL AUTO_INCREMENT,
  `INDEX_NO` int NOT NULL,
  `LANGUAGE_NAME` varchar(25) DEFAULT NULL,
  `LAVEL_EXPERIENCE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`LANGUAGE_ID`),
  UNIQUE KEY `LANGUAGE_ID_UNIQUE` (`LANGUAGE_ID`),
  KEY `KNOWN_LANGUAGE_ibfk_1` (`INDEX_NO`),
  CONSTRAINT `KNOWN_LANGUAGE_ibfk_1` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=74 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `KNOWN_TECHNOLOGIES` (
  `TECHNOLOGY_ID` int NOT NULL AUTO_INCREMENT,
  `INDEX_NO` int NOT NULL,
  `TECHNOLOGY_NAME` varchar(45) DEFAULT NULL,
  `LAVEL_EXPERIENCE` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`TECHNOLOGY_ID`),
  UNIQUE KEY `TECHNOLOGY_ID_UNIQUE` (`TECHNOLOGY_ID`),
  KEY `KNOWN_TECHNOLOGIES_ibfk_1` (`INDEX_NO`),
  CONSTRAINT `KNOWN_TECHNOLOGIES_ibfk_1` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PREFERANCES` (
  `INDEX_NO` int DEFAULT NULL,
  `LOCATION_NAME` varchar(45) DEFAULT NULL,
  `NOTICE_TIME` varchar(45) DEFAULT NULL,
  `EXPECTED_CTC` bigint DEFAULT NULL,
  `CURRENT_CTC` bigint DEFAULT NULL,
  `DEPARTMENT` varchar(45) DEFAULT NULL,
  KEY `PREFERANCES_ibfk_1` (`INDEX_NO`),
  CONSTRAINT `PREFERANCES_ibfk_1` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `REFERANCE_CONTACT` (
  `REFERANCE_NO` int NOT NULL AUTO_INCREMENT,
  `INDEX_NO` int DEFAULT NULL,
  `REFER_INDEX` int DEFAULT NULL,
  `NAME_OF_PERSON` varchar(45) DEFAULT NULL,
  `CONTECT_NO` bigint DEFAULT NULL,
  `RELATION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`REFERANCE_NO`),
  UNIQUE KEY `REFERANCE_NO_UNIQUE` (`REFERANCE_NO`),
  KEY `REFERANCE_CONTACT_ibfk_1` (`INDEX_NO`),
  CONSTRAINT `REFERANCE_CONTACT_ibfk_1` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `WORK_EXPERIENCE` (
  `EXPERIENCE_NO` int NOT NULL AUTO_INCREMENT,
  `INDEX_NO` int DEFAULT NULL,
  `COMPANY_ID` int DEFAULT NULL,
  `COMPANY_NAME` varchar(45) DEFAULT NULL,
  `DESIGNATION` varchar(40) DEFAULT NULL,
  `FORM` date DEFAULT NULL,
  `TO_DATE` date DEFAULT NULL,
  PRIMARY KEY (`EXPERIENCE_NO`),
  UNIQUE KEY `EXPERIENCE_NO_UNIQUE` (`EXPERIENCE_NO`),
  KEY `WORK_EXPERIENCE_ibfk_1` (`INDEX_NO`),
  CONSTRAINT `WORK_EXPERIENCE_ibfk_1` FOREIGN KEY (`INDEX_NO`) REFERENCES `JOB_APPLICATION_FORM` (`INDEX_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;